# Generated by Django 4.2 on 2025-05-15 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cxc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almacen', models.IntegerField(unique=True)),
                ('nombre', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClaveMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_movimiento', models.CharField(default='', max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('tipo', models.CharField(default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=' ', max_length=30)),
                ('clave', models.CharField(max_length=10, unique=True)),
                ('simbolo', models.CharField(blank=True, max_length=5, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='', max_length=12)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, upload_to='productos')),
                ('precio1', models.DecimalField(decimal_places=2, max_digits=9)),
                ('precio2', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('precio3', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('precio4', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('precio5', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('precio6', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('maximo', models.IntegerField(default=0)),
                ('minimo', models.IntegerField(default=0)),
                ('reorden', models.IntegerField(default=0)),
                ('fecha_registro', models.DateField()),
                ('descuento_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_reposicion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=4, max_digits=10)),
                ('campo_libre_str', models.CharField(blank=True, default='', max_length=50)),
                ('campo_libre_num', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=' ', max_length=100)),
                ('direccion', models.TextField(default='', null=True)),
                ('contacto', models.CharField(default='', max_length=100)),
                ('telefono1', models.CharField(default='', max_length=20)),
                ('telefono2', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('plazo_credito', models.SmallIntegerField(default=0)),
                ('comentarios', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_medida', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Traspaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=7)),
                ('fecha_traspaso', models.DateField()),
                ('alm1', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='traspasos_salida', to='inv.almacen')),
                ('alm2', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='traspasos_entrada', to='inv.almacen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaldoInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha', models.DateField()),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Remision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_remision', models.CharField(default='', max_length=7)),
                ('fecha_remision', models.DateField()),
                ('numero_factura', models.CharField(default='', max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('C', 'Cotizacion'), ('P', 'Pedido'), ('R', 'Remisionado'), ('F', 'Facturado'), ('E', 'Eliminada')], default='R', max_length=1)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.almacen')),
                ('clave_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.clavemovimiento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cxc.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_de_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.unidadmedida'),
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=7)),
                ('move_s', models.CharField(max_length=1)),
                ('fecha_movimiento', models.DateField()),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.almacen')),
                ('clave_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.clavemovimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleTraspaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.producto')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.traspaso')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('numero_remision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inv.remision')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('costo_unit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.producto')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inv.movimiento')),
            ],
        ),
    ]
