# Generated by Django 4.2 on 2025-05-16 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(default='', max_length=7)),
                ('pedido', models.CharField(blank=True, default='', max_length=7)),
                ('fecha_compra', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pagada', models.DateField()),
                ('paridad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('flete', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('descuento_pp', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.almacen')),
                ('clave_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.clavemovimiento')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.moneda')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.proveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('costo_unit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.producto')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inv.compra')),
            ],
        ),
    ]
