# Generated by Django 4.2 on 2025-05-02 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=' ', max_length=30)),
                ('clave', models.CharField(max_length=10, unique=True)),
                ('simbolo', models.CharField(blank=True, max_length=5, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='detallemovimiento',
            old_name='descuento',
            new_name='costo_unit',
        ),
        migrations.RenameField(
            model_name='remision',
            old_name='clave_remision',
            new_name='clave_movimiento',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='subcategoria',
        ),
        migrations.RemoveField(
            model_name='detallemovimiento',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='campo_libre_real',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='subcategoria',
        ),
        migrations.RemoveField(
            model_name='remision',
            name='estado',
        ),
        migrations.AddField(
            model_name='producto',
            name='campo_libre_num',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='remision',
            name='almacen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='inv.almacen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remision',
            name='status',
            field=models.CharField(choices=[('C', 'Cotizacion'), ('P', 'Pedido'), ('R', 'Remisionado'), ('F', 'Facturado'), ('E', 'Eliminada')], default='R', max_length=1),
        ),
        migrations.AddField(
            model_name='remision',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='almacen',
            name='almacen',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='clavemovimiento',
            name='clave_movimiento',
            field=models.CharField(default='', max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='detallemovimiento',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.producto'),
        ),
        migrations.AlterField(
            model_name='detallemovimiento',
            name='referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inv.movimiento'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio6',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono2',
            field=models.CharField(default='', max_length=20),
        ),
    ]
