# Generated by Django 4.2 on 2025-06-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadmedida',
            name='unidad_medida',
            field=models.CharField(max_length=3),
        ),
    ]
