# Generated by Django 4.2 on 2025-06-14 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fecha_registro', models.DateField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='remision',
            name='vendedor',
            field=models.ForeignKey(default=2025061, on_delete=django.db.models.deletion.RESTRICT, to='inv.vendedor'),
            preserve_default=False,
        ),
    ]
