# Generated by Django 4.2 on 2025-06-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='usuario',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='usuario',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='usuario',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='remision',
            name='usuario',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='traspaso',
            name='usuario',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
