# Generated by Django 4.2 on 2025-06-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_alter_unidadmedida_unidad_medida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='unidad_de_medida',
            new_name='unidad_medida',
        ),
    ]
