# Generated by Django 4.2 on 2025-04-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='moneda',
            name='clave',
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moneda',
            name='simbolo',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
