# Generated by Django 4.2 on 2025-06-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_vendedor_remision_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='vendedor',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
