# Generated by Django 4.2 on 2025-05-12 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_moneda_rename_descuento_detallemovimiento_costo_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='clavemovimiento',
            name='tipo',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='detalleremision',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detalleremision',
            name='numero_remision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inv.remision'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='referencia',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='remision',
            name='numero_remision',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='traspaso',
            name='referencia',
            field=models.CharField(max_length=7),
        ),
    ]
