# Generated by Django 4.2 on 2025-07-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_alter_compra_usuario_alter_cotizacion_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='comentarios',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='plazo_credito',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono2',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
