# Generated by Django 4.2 on 2025-06-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_alter_vendedor_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remision',
            name='status',
            field=models.CharField(choices=[('C', 'COTIZACION'), ('P', 'PEDIDO'), ('R', 'REMISION'), ('F', 'FACTURADO'), ('E', 'ELIMINADA')], default='R', max_length=1),
        ),
    ]
