# Generated by Django 4.2 on 2025-07-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_alter_proveedor_comentarios_alter_proveedor_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='plazo_credito',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
