# Generated by Django 4.2 on 2025-06-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_rename_unidad_de_medida_producto_unidad_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ieps',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
