# Generated by Django 4.2 on 2025-04-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_moneda_activa_moneda_clave_moneda_simbolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='almacen',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='clavemovimiento',
            name='clave_movimiento',
            field=models.CharField(default='01', max_length=2, unique=True),
        ),
    ]
