# Generated by Django 4.2 on 2025-06-17 18:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_alter_remision_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleremision',
            name='ieps_producto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleremision',
            name='iva_producto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleremision',
            name='objeto_impuesto',
            field=models.CharField(default='02', max_length=3),
        ),
        migrations.AddField(
            model_name='detalleremision',
            name='retencion_isr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleremision',
            name='retencion_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleremision',
            name='tasa_ieps',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='detalleremision',
            name='tasa_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='detalleremision',
            name='tasa_retencion_isr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='detalleremision',
            name='tasa_retencion_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
    ]
