# Generated by Django 4.2 on 2025-04-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_alter_almacen_almacen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='catalogo'),
        ),
    ]
