# Generated by Django 4.2 on 2025-07-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_alter_proveedor_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='plazo_credito',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
