# Generated by Django 4.2 on 2025-06-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_producto_ieps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ieps',
            field=models.BooleanField(blank=True, default='False'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='iva',
            field=models.BooleanField(blank=True, default='False'),
        ),
    ]
