# Generated by Django 4.2 on 2025-05-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_producto_clave_sat'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='paridad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
