# Generated by Django 4.2 on 2025-06-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_detalleremision_ieps_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleremision',
            name='objeto_impuesto',
        ),
    ]
