# Generated by Django 4.2 on 2025-06-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_alter_producto_ieps_alter_producto_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ieps',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='iva',
            field=models.BooleanField(blank=True),
        ),
    ]
