# Generated by Django 4.2 on 2025-04-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_alter_producto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='campo_libre_real',
            new_name='campo_libre_num',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='subcategoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='subcategoria',
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio6',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
