# Generated by Django 4.2 on 2025-06-18 04:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_remove_detalleremision_objeto_impuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleremision',
            name='tasa_ieps',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='detalleremision',
            name='tasa_iva',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='detalleremision',
            name='tasa_retencion_isr',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='detalleremision',
            name='tasa_retencion_iva',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9),
        ),
    ]
