# Generated by Django 4.2 on 2025-04-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_rename_campo_libre_real_producto_campo_libre_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='campo_libre_num',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True),
        ),
    ]
