# Generated by Django 4.2 on 2025-06-05 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_alter_producto_ieps_alter_producto_iva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descuento_venta',
            new_name='precio_promocion',
        ),
    ]
