# Generated by Django 4.2 on 2025-06-08 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0007_rename_descuento_venta_producto_precio_promocion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='ieps',
            new_name='aplica_ieps',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='iva',
            new_name='aplica_iva',
        ),
    ]
