# Generated by Django 4.2 on 2025-04-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0007_alter_producto_campo_libre_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='telefono1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono2',
            field=models.CharField(default='', max_length=20),
        ),
    ]
