# Generated by Django 4.2 on 2025-06-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0008_cotizacion_detallecotizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clavemovimiento',
            name='es_compra',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clavemovimiento',
            name='es_remision',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
