# Generated by Django 4.2 on 2025-04-24 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0008_alter_proveedor_telefono1_alter_proveedor_telefono2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallemovimiento',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.producto'),
        ),
        migrations.AlterField(
            model_name='detallemovimiento',
            name='referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inv.movimiento'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='referencia',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='productos'),
        ),
    ]
