# Generated by Django 4.2 on 2025-04-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0009_alter_detallemovimiento_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clavemovimiento',
            name='clave_movimiento',
            field=models.CharField(default='', max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='referencia',
            field=models.CharField(max_length=8),
        ),
    ]
