# Generated by Django 4.2 on 2025-04-30 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0010_alter_clavemovimiento_clave_movimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallemovimiento',
            old_name='descuento',
            new_name='costo_unit',
        ),
        migrations.RemoveField(
            model_name='detallemovimiento',
            name='precio',
        ),
    ]
