version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: gunicorn admin.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/code/static
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
