
services:
  web:
    build:
      context: ./admin
      dockerfile: docker/Dockerfile
    command: gunicorn admin.wsgi:application --bind 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=admin.settings.prod
    ports:
      - "8000"
    volumes:
      - ./staticfiles:/admin/staticfiles
      - ./media:/admin/media
    env_file:
      - ./admin/.env
    depends_on:
      - db

  webapp:
    build:
      context: ./switchh
      dockerfile: docker/Dockerfile.webapp
    command: gunicorn switchh.wsgi:application --bind 0.0.0.0:8001
    environment:
      - DJANGO_SETTINGS_MODULE=switchh.settings
    ports:
      - "8001"
    volumes:
      - ./webapp_static:/webapp/staticfiles
      - ./webapp_media:/webapp/media
    env_file:
      - ./switchh/.env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:14
#    ports:
#      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/admin/staticfiles
      - ./media:/admin/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
