
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: >
      gunicorn admin.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      --timeout 120
      --graceful-timeout 30
      --log-level info

    environment:
      - DJANGO_SETTINGS_MODULE=admin.settings.prod
    ports:
      - "8000"
    volumes:
      - ./staticfiles:/admin/staticfiles
      - ./media:/admin/media
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/admin/staticfiles
      - ./media:/admin/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot

    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
