# Generated by Django 4.2 on 2025-04-21 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('id_empresa', models.CharField(max_length=8)),
                ('activa', models.BooleanField(default=False)),
                ('directorio', models.CharField(blank=True, max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('almacen_actual', models.IntegerField(default=1)),
                ('almacen_facturacion', models.IntegerField(default=1)),
                ('decimales_unidades', models.SmallIntegerField(default=2)),
                ('decimales_importe', models.SmallIntegerField(default=2)),
                ('cuenta_iva', models.CharField(blank=True, max_length=24)),
                ('clave_compras', models.CharField(default='CO', max_length=2)),
                ('clave_traspasos', models.CharField(default='TR', max_length=2)),
                ('clave_remision', models.CharField(default='RE', max_length=2)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=9)),
                ('retencion_iva', models.DecimalField(decimal_places=5, max_digits=9)),
                ('retencion_isr', models.DecimalField(decimal_places=5, max_digits=9)),
                ('ieps', models.DecimalField(decimal_places=5, max_digits=9)),
                ('ip', models.CharField(max_length=24)),
                ('comentarios', models.TextField(blank=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
