# Generated by Django 4.2 on 2025-04-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='fecha_renovacion',
            field=models.DateField(default='2025-09-30'),
            preserve_default=False,
        ),
    ]
