# Generated by Django 4.2 on 2025-06-24 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('cxc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='regimen_fiscal',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.RESTRICT, to='cxc.regimenfiscal'),
        ),
        migrations.AddField(
            model_name='certificadocsd',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
    ]
