# Generated by Django 4.2 on 2025-06-06 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='ieps',
            new_name='tasa_ieps',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='iva',
            new_name='tasa_iva',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='retencion_isr',
            new_name='tasa_retencion_isr',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='retencion_iva',
            new_name='tasa_retencion_iva',
        ),
    ]
