# Generated by Django 4.2 on 2025-06-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='clave_remision',
            field=models.CharField(default='R1', max_length=2),
        ),
    ]
