# Generated by Django 4.2 on 2025-06-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tipo_usuario',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
