# Generated by Django 4.2 on 2025-04-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_fecha_renovacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='factor',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
