# Generated by Django 4.2 on 2025-06-27 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cxc', '0002_initial'),
        ('core', '0003_perfilusuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='regimen_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cxc.regimenfiscal'),
        ),
    ]
