# Generated by Django 4.2 on 2025-04-27 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_empresa_id_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='id_empresa',
            new_name='num_empresa',
        ),
    ]
