# Generated by Django 4.2 on 2025-06-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_empresa_regimen_fiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresadb',
            name='db_port',
            field=models.CharField(default='3306', max_length=10),
        ),
    ]
