# Generated by Django 4.2 on 2025-05-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_id_empresa_empresa_num_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='nombre',
            new_name='calle',
        ),
        migrations.AddField(
            model_name='empresa',
            name='calle_expedicion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='empresa',
            name='codigo_postal_expedicion',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='empresa',
            name='colonia',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='empresa',
            name='colonia_expedicion',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado_expedicion',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='localidad',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='empresa',
            name='localidad_expedicion',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='empresa',
            name='municipio',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='empresa',
            name='municipio_expedicion',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_fiscal',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero_exterior',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero_exterior_expedicion',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero_interior',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero_interior_expedicion',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pagina_web',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pais',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pais_expedicion',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='regimen_de_sociedad',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='empresa',
            name='regimen_fiscal',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='empresa',
            name='representante',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='rfc',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='empresa',
            name='rutaXML',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
