# Generated by Django 4.2 on 2025-07-02 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_empresadb_db_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresadb',
            name='empresa',
            field=models.OneToOneField(default=40, on_delete=django.db.models.deletion.CASCADE, related_name='db_config', to='core.empresa'),
            preserve_default=False,
        ),
    ]
