# Generated by Django 4.2 on 2025-05-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_nombre_empresa_calle_empresa_calle_expedicion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='rutaXML',
            new_name='ruta_xml',
        ),
    ]
