# Generated by Django 4.2 on 2025-07-03 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_empresadb_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresadb',
            name='empresa',
        ),
    ]
