# Generated by Django 4.2 on 2025-07-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_empresadb_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='db_name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
