# Generated by Django 4.2 on 2025-05-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_rutaxml_empresa_ruta_xml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='almacen_facturacion',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='decimales_importe',
            field=models.SmallIntegerField(blank=True, default=2),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='decimales_unidades',
            field=models.SmallIntegerField(blank=True, default=2),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='factor',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ip',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
