# Generated by Django 4.2 on 2025-05-22 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_certificadocsd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificadocsd',
            old_name='archivo_cer',
            new_name='cer_archivo',
        ),
        migrations.RenameField(
            model_name='certificadocsd',
            old_name='archivo_key',
            new_name='key_archivo',
        ),
        migrations.RenameField(
            model_name='certificadocsd',
            old_name='contrasena',
            new_name='password',
        ),
    ]
