# Generated by Django 4.2 on 2025-05-24 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cxc', '0002_initial'),
        ('inv', '0005_moneda_paridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exportacion', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pago', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso'), ('T', 'Traslado')], max_length=1)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UsoCfdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uso_cfdi', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_remision', models.CharField(default='', max_length=7)),
                ('serie_emisor', models.CharField(default='', max_length=50)),
                ('serie_sat', models.CharField(default='', max_length=50)),
                ('numero_factura', models.CharField(default='', max_length=20)),
                ('fecha_emision', models.DateField()),
                ('fecha_hora_certificacion', models.DateField()),
                ('lugar_expedicion', models.CharField(default='', max_length=5)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impuestos_trasladados', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuestos_retenidos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('B', 'Borrador'), ('T', 'Timbrado'), ('C', 'Cancelado')], default='B', max_length=1)),
                ('xml', models.FileField(blank=True, null=True, upload_to='cfdi/xml/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='cfdi/pdf/')),
                ('uuid', models.CharField(blank=True, max_length=40)),
                ('fecha_timbrado', models.DateTimeField(blank=True, null=True)),
                ('sello_cfdi', models.TextField(blank=True)),
                ('no_certificado_sat', models.CharField(blank=True, max_length=20)),
                ('estatus', models.CharField(default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('clave_remision', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.clavemovimiento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cxc.cliente')),
                ('exportacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fac.exportacion')),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fac.formapago')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fac.metodopago')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.moneda')),
                ('tipo_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fac.tipocomprobante')),
                ('uso_cfdi', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fac.usocfdi')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_prod_serv', models.CharField(max_length=10)),
                ('clave_unidad', models.CharField(max_length=5)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tasa_iva', models.DecimalField(decimal_places=2, default=16.0, max_digits=5)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('objeto_imp', models.CharField(default='02', max_length=3)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='fac.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.producto')),
            ],
        ),
    ]
