# Generated by Django 4.2 on 2025-05-29 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_moneda_paridad'),
        ('fac', '0002_alter_factura_numero_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='clave_remision',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='inv.clavemovimiento'),
        ),
    ]
