# Generated by Django 4.2 on 2025-07-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0002_alter_factura_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='usuario',
            field=models.CharField(blank=True, max_length=41),
        ),
    ]
