# Generated by Django 4.2 on 2025-06-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0002_catalogos_iniciales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='no_certificado_sat',
            new_name='num_certificado',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='sello_cfdi',
            new_name='sello',
        ),
        migrations.AddField(
            model_name='factura',
            name='rfc_certifico',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='factura',
            name='sello_sat',
            field=models.TextField(blank=True),
        ),
    ]
