# Generated by Django 4.2 on 2025-06-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0003_rename_no_certificado_sat_factura_num_certificado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='fecha_hora_certificacion',
        ),
        migrations.AlterField(
            model_name='factura',
            name='estatus',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('VIGENTE', 'Vigente'), ('CANCELADA', 'Cancelado'), ('ERROR', 'Error')], default='BORRADOR', max_length=10),
        ),
    ]
