# Generated by Django 4.2 on 2025-06-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0003_catalogos_iniciales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='status',
        ),
        migrations.AlterField(
            model_name='factura',
            name='estatus',
            field=models.CharField(default='BORRADOR', max_length=20),
        ),
    ]
