# Generated by Django 4.2 on 2025-05-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0003_alter_factura_clave_remision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapago',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='usocfdi',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
