# Generated by Django 4.2 on 2025-06-15 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0004_remove_factura_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='serie_sat',
        ),
    ]
