# Generated by Django 4.2 on 2025-06-18 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0005_remove_factura_serie_sat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='descuento',
            new_name='descuento_factura',
        ),
    ]
