# Generated by Django 4.2 on 2025-06-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0005_catalogos_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='condiciones_pago',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
