# Generated by Django 4.2 on 2025-06-18 04:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0006_rename_descuento_factura_descuento_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='tasa_retencion_isr',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='tasa_retencion_iva',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=9),
        ),
    ]
