# Generated by Django 4.2 on 2025-06-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0006_factura_condiciones_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estatus',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('TIMBRADA', 'Timbrado'), ('CANCELADA', 'Cancelado'), ('ERROR', 'Error')], default='BORRADOR', max_length=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='no_certificado_sat',
            field=models.CharField(blank=True, max_length=21),
        ),
    ]
