# Generated by Django 4.2 on 2025-05-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0004_alter_formapago_nombre_alter_metodopago_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usocfdi',
            name='nombre',
            field=models.CharField(max_length=106),
        ),
    ]
