# Generated by Django 4.2 on 2025-06-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0007_alter_factura_estatus_alter_factura_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='condiciones_pago',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
