# Generated by Django 4.2 on 2025-06-18 04:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0007_alter_detallefactura_tasa_retencion_isr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='tasa_ieps',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='tasa_iva',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='tasa_retencion_isr',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='tasa_retencion_iva',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9),
        ),
    ]
