# Generated by Django 4.2 on 2025-06-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0010_alter_factura_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estatus',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Vigente', 'Vigente'), ('Cancelada', 'Cancelado'), ('Error', 'Error')], default='Borrador', max_length=10),
        ),
    ]
