# Generated by Django 4.2 on 2025-06-07 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0010_detallefactura_ieps_detallefactura_retencion_isr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallefactura',
            old_name='ieps',
            new_name='ieps_producto',
        ),
        migrations.RenameField(
            model_name='detallefactura',
            old_name='iva',
            new_name='iva_producto',
        ),
    ]
