# Generated by Django 4.2 on 2025-06-09 05:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0011_rename_ieps_detallefactura_ieps_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='tasa_retencion_isr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='tasa_retencion_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
    ]
