# Generated by Django 4.2 on 2025-06-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0011_alter_factura_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
