# Generated by Django 4.2 on 2025-06-09 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_ieps_empresa_tasa_ieps_and_more'),
        ('fac', '0012_detallefactura_tasa_retencion_isr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.empresa'),
            preserve_default=False,
        ),
    ]
