# Generated by Django 4.2 on 2025-06-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0013_factura_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='ieps_factura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='factura',
            name='iva_factura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='factura',
            name='retencion_isr_factura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='factura',
            name='retencion_iva_factura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
