# Generated by Django 4.2 on 2025-04-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=8)),
                ('fecha_movimiento', models.DateField()),
                ('concepto', models.CharField(blank=True, max_length=50)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_cargo', models.CharField(max_length=8)),
                ('concepto', models.CharField(blank=True, max_length=50)),
                ('fecha_movimiento', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateField(blank=True)),
                ('saldada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClaveMovimientoCxC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_movimiento', models.CharField(default='01', max_length=2)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('tipo', models.CharField(default='C', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.IntegerField(default=1)),
                ('nombre', models.CharField(max_length=100)),
                ('rfc', models.CharField(blank=True, max_length=13)),
                ('telefono', models.CharField(blank=True, max_length=12)),
                ('direccion', models.TextField(blank=True, default='')),
                ('codigo_postal', models.CharField(blank=True, default='', max_length=5)),
                ('ciudad', models.CharField(blank=True, default='', max_length=100)),
                ('direccion_entrega', models.TextField(blank=True, default='')),
                ('codigo_postal_entrega', models.CharField(blank=True, default='', max_length=5)),
                ('ciudad_entrega', models.CharField(blank=True, default='', max_length=100)),
                ('telefono1', models.CharField(blank=True, default='', max_length=13)),
                ('telefono2', models.CharField(blank=True, default='', max_length=13)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('plazo_credito', models.SmallIntegerField(default=0, null=True)),
                ('limite_credito', models.BigIntegerField(default=0, null=True)),
                ('cuenta_cnt', models.CharField(blank=True, default='', max_length=24)),
                ('retencion_iva', models.BooleanField(blank=True, default='False')),
                ('retencion_isr', models.BooleanField(blank=True, default='False')),
                ('ieps', models.BooleanField(default='False')),
                ('campo_libre_str', models.CharField(blank=True, default='', max_length=50)),
                ('campo_libre_real', models.FloatField(default=0, null=True)),
                ('comentarios', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='SaldoInicialCxC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.SmallIntegerField(default=1)),
                ('nombre', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
