# Generated by Django 4.2 on 2025-06-24 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inv', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cxc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldoinicialcxc',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.almacen'),
        ),
        migrations.AddField(
            model_name='saldoinicialcxc',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cxc.cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='regimen_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cxc.regimenfiscal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cxc.tipocliente'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.almacen'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='clave_movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cxc.clavemovimientocxc'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cxc.cliente'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abono',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.almacen'),
        ),
        migrations.AddField(
            model_name='abono',
            name='clave_movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cxc.clavemovimientocxc'),
        ),
        migrations.AddField(
            model_name='abono',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cxc.cliente'),
        ),
        migrations.AddField(
            model_name='abono',
            name='referencia_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cxc.cargo'),
        ),
        migrations.AddField(
            model_name='abono',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
