# Generated by Django 4.2 on 2025-06-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxc', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regimenfiscal',
            name='nombre',
            field=models.CharField(max_length=110),
        ),
    ]
