# Generated by Django 4.2 on 2025-04-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxc', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clavemovimientocxc',
            name='clave_movimiento',
            field=models.SmallIntegerField(default=1),
        ),
    ]
