# Generated by Django 4.2 on 2025-04-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxc', '0003_alter_clavemovimientocxc_clave_movimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='tipoCliente',
            new_name='tipo_cliente',
        ),
        migrations.RenameField(
            model_name='tipocliente',
            old_name='tipo',
            new_name='tipo_cliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='campo_libre_real',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.AddField(
            model_name='cliente',
            name='campo_libre_num',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
