# Generated by Django 4.2 on 2025-07-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxc', '0003_alter_tipocliente_tipo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocliente',
            name='tipo_cliente',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
