# Generated by Django 4.2 on 2025-06-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxc', '0004_rename_direccion_cliente_calle_cliente_colonia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ieps',
            field=models.BooleanField(blank=True, default='False'),
        ),
    ]
