# Generated by Django 4.2 on 2025-06-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxc', '0005_alter_cliente_ieps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='calle',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
