# Generated by Django 4.2 on 2025-06-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxc', '0006_alter_cliente_calle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
