# Generated by Django 4.2 on 2025-06-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxc', '0007_alter_cliente_colonia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ieps',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='retencion_isr',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='retencion_iva',
            field=models.BooleanField(blank=True),
        ),
    ]
