# Generated by Django 4.2 on 2025-06-08 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cxc', '0008_alter_cliente_ieps_alter_cliente_retencion_isr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='ieps',
            new_name='aplica_retencion_isr',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='retencion_isr',
            new_name='aplica_retencion_iva',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='retencion_iva',
        ),
    ]
