# Generated by Django 4.2 on 2025-04-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='almacen',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='nombre',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='subcategoria',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='campo_libre_real',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='campo_libre_str',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ciudad_entrega',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo_postal_entrega',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='comentarios',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cuenta_cnt',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion_entrega',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='limite_credito',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='plazo_credito',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='retencion_isr',
            field=models.BooleanField(blank=True, default='False'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='retencion_iva',
            field=models.BooleanField(blank=True, default='False'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono1',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono2',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='detalleremision',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='almacen_actual',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='almacen_facturacion',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='nombre',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='campo_libre_real',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='campo_libre_str',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='subcategoria',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='comentarios',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono1',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono2',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='remision',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='remision',
            name='numero_factura',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='remision',
            name='numero_remision',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='tipocliente',
            name='nombre',
            field=models.CharField(blank=True, default=1, max_length=30),
            preserve_default=False,
        ),
    ]
