# Generated by Django 4.2 on 2025-04-18 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_almacen_almacen_alter_almacen_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saldoinicial',
            old_name='Existencia',
            new_name='existencia',
        ),
        migrations.AlterField(
            model_name='detallemovimiento',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.producto'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='decimales_importe',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='decimales_unidades',
            field=models.SmallIntegerField(default=2),
        ),
    ]
