# Generated by Django 4.2 on 2025-08-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='num_usuarios',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
    