# Generated by Django 4.2 on 2025-08-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_num_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje1', models.CharField(blank=True, max_length=200)),
                ('mensaje2', models.CharField(blank=True, max_length=200)),
                ('mensaje3', models.CharField(blank=True, max_length=200)),
                ('mensaje4', models.CharField(blank=True, max_length=200)),
                ('mensaje5', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Mensajes de inicio',
                'verbose_name_plural': 'Mensajes de inicio',
            },
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='num_usuarios',
        ),
        migrations.AddField(
            model_name='empresadb',
            name='num_usuarios',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
    