# Generated by Django 4.2 on 2025-08-03 16:50

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cxc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almacen', models.IntegerField(unique=True)),
                ('nombre', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClaveMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_movimiento', models.CharField(default='', max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('tipo', models.CharField(default='', max_length=1)),
                ('es_remision', models.BooleanField(blank=True)),
                ('es_compra', models.BooleanField(blank=True)),
                ('es_servicio', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=40)),
                ('referencia', models.CharField(default='', max_length=7)),
                ('pedido', models.CharField(blank=True, default='', max_length=7)),
                ('fecha_compra', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pagada', models.DateField()),
                ('paridad', models.DecimalField(decimal_places=4, max_digits=10)),
                ('flete', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('descuento_pp', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.almacen')),
                ('clave_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.clavemovimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=40)),
                ('numero_cotizacion', models.CharField(default='', max_length=7)),
                ('fecha_cotizacion', models.DateField()),
                ('comentarios', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cxc.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=' ', max_length=30)),
                ('clave', models.CharField(max_length=10, unique=True)),
                ('simbolo', models.CharField(blank=True, max_length=5, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('paridad', models.DecimalField(decimal_places=6, default=1, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='', max_length=12)),
                ('clave_sat', models.CharField(default='', max_length=8)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, upload_to='productos')),
                ('precio1', models.DecimalField(decimal_places=2, max_digits=9)),
                ('precio2', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('precio3', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('precio4', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('precio5', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('precio6', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('maximo', models.IntegerField(default=0)),
                ('minimo', models.IntegerField(default=0)),
                ('reorden', models.IntegerField(default=0)),
                ('fecha_registro', models.DateField()),
                ('precio_promocion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_reposicion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aplica_iva', models.BooleanField(blank=True)),
                ('aplica_ieps', models.BooleanField(blank=True)),
                ('tasa_ieps', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9)),
                ('campo_libre_str', models.CharField(blank=True, default='', max_length=50)),
                ('campo_libre_num', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=' ', max_length=100)),
                ('direccion', models.TextField(blank=True)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono1', models.CharField(blank=True, max_length=20)),
                ('telefono2', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('plazo_credito', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('comentarios', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_medida', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fecha_registro', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Traspaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=40)),
                ('referencia', models.CharField(max_length=7)),
                ('fecha_traspaso', models.DateField()),
                ('alm1', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='traspasos_salida', to='inv.almacen')),
                ('alm2', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='traspasos_entrada', to='inv.almacen')),
            ],
        ),
        migrations.CreateModel(
            name='SaldoInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha', models.DateField()),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Remision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=40)),
                ('numero_remision', models.CharField(default='', max_length=7)),
                ('fecha_remision', models.DateField()),
                ('numero_factura', models.CharField(default='', max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('C', 'COTIZACION'), ('P', 'PEDIDO'), ('R', 'REMISION'), ('F', 'FACTURADO'), ('E', 'ELIMINADA')], default='R', max_length=1)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.almacen')),
                ('clave_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.clavemovimiento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cxc.cliente')),
                ('numero_cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='inv.cotizacion')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.vendedor')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.unidadmedida'),
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=40)),
                ('referencia', models.CharField(max_length=7)),
                ('move_s', models.CharField(max_length=1)),
                ('fecha_movimiento', models.DateField()),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.almacen')),
                ('clave_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.clavemovimiento')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleTraspaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.producto')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.traspaso')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tasa_iva', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9)),
                ('iva_producto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('tasa_ieps', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9)),
                ('ieps_producto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('tasa_retencion_iva', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9)),
                ('tasa_retencion_isr', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9)),
                ('retencion_iva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('retencion_isr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('numero_remision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inv.remision')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('costo_unit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.producto')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inv.movimiento')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('numero_cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inv.cotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('costo_unit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.producto')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inv.compra')),   
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.vendedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.moneda'),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.proveedor'),
        ),
    ]
    