# Generated by Django 4.2 on 2025-07-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=8)),
                ('fecha_movimiento', models.DateField()),
                ('concepto', models.CharField(blank=True, max_length=50)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_cargo', models.CharField(max_length=8)),
                ('concepto', models.CharField(blank=True, max_length=50)),
                ('fecha_movimiento', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateField(blank=True)),
                ('saldada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClaveMovimientoCxC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_movimiento', models.SmallIntegerField(default=1)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('tipo', models.CharField(default='C', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=6, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('rfc', models.CharField(blank=True, max_length=13)),
                ('calle', models.CharField(blank=True, default='', max_length=50)),
                ('numero_exterior', models.CharField(blank=True, max_length=10)),
                ('numero_interior', models.CharField(blank=True, max_length=10)),
                ('colonia', models.CharField(blank=True, max_length=30)),
                ('codigo_postal', models.CharField(blank=True, default='', max_length=5)),
                ('ciudad', models.CharField(blank=True, default='', max_length=100)),
                ('municipio', models.CharField(blank=True, default='', max_length=100)),
                ('estado', models.CharField(blank=True, default='', max_length=30)),
                ('direccion_entrega', models.TextField(blank=True, default='')),
                ('codigo_postal_entrega', models.CharField(blank=True, default='', max_length=5)),
                ('ciudad_entrega', models.CharField(blank=True, default='', max_length=100)),
                ('telefono1', models.CharField(blank=True, default='', max_length=20)),
                ('telefono2', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('plazo_credito', models.SmallIntegerField(default=0, null=True)),
                ('limite_credito', models.BigIntegerField(default=0, null=True)),
                ('cuenta_cnt', models.CharField(blank=True, default='', max_length=24)),
                ('aplica_retencion_iva', models.BooleanField(blank=True)),
                ('aplica_retencion_isr', models.BooleanField(blank=True)),
                ('campo_libre_str', models.CharField(blank=True, default='', max_length=50)),
                ('campo_libre_num', models.FloatField(blank=True, default=0, null=True)),
                ('comentarios', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='RegimenFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regimen_fiscal', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=110)),
            ],
        ),
        migrations.CreateModel(
            name='SaldoInicialCxC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.SmallIntegerField(unique=True)),
                ('nombre', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
