# Generated by Django 4.2 on 2025-08-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxc', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email2',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email3',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
    