# Generated by Django 4.2 on 2025-08-07 19:02

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inv', '0001_initial'),
        ('cxc', '0002_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exportacion', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pago', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso'), ('T', 'Traslado')], max_length=1)),      
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UsoCfdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uso_cfdi', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=106)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=41)),
                ('numero_remision', models.CharField(default='', max_length=7)),
                ('numero_factura', models.CharField(default='', max_length=7)),
                ('fecha_emision', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento_factura', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iva_factura', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ieps_factura', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('retencion_iva_factura', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('retencion_isr_factura', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuestos_trasladados', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuestos_retenidos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('serie_emisor', models.CharField(default='', max_length=50)),
                ('lugar_expedicion', models.CharField(default='', max_length=5)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('condiciones_pago', models.CharField(default='1', max_length=30)),
                ('xml', models.FileField(blank=True, null=True, upload_to='cfdi/xml/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='cfdi/pdf/')),
                ('uuid', models.CharField(blank=True, max_length=40)),
                ('fecha_timbrado', models.DateTimeField(blank=True, null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('sello', models.TextField(blank=True)),
                ('sello_sat', models.TextField(blank=True)),
                ('num_certificado', models.CharField(blank=True, max_length=21)),
                ('rfc_certifico', models.CharField(blank=True, max_length=13)),
                ('estatus', models.CharField(choices=[('Borrador', 'Borrador'), ('Vigente', 'Vigente'), ('Cancelada', 'Cancelado'), ('Error', 'Error')], default='Borrador', max_length=10)),
                ('clave_remision', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='inv.clavemovimiento')), 
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cxc.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.empresa')),
                ('exportacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fac.exportacion')),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fac.formapago')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fac.metodopago')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.moneda')),
                ('tipo_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fac.tipocomprobante')),
                ('uso_cfdi', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fac.usocfdi')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_prod_serv', models.CharField(max_length=10)),
                ('clave_unidad', models.CharField(max_length=5)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('tasa_iva', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9)),
                ('iva_producto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('tasa_ieps', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9)),
                ('ieps_producto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('tasa_retencion_iva', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9)),
                ('tasa_retencion_isr', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=9)),
                ('retencion_iva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('retencion_isr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('objeto_impuesto', models.CharField(default='02', max_length=3)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='fac.factura')),    
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inv.producto')),
            ],
        ),
    ]
    