# Generated by Django 4.2 on 2025-08-26 17:50

from django.db import migrations, models
import fac.models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=fac.models.factura_pdf_path),
        ),
        migrations.AlterField(
            model_name='factura',
            name='xml',
            field=models.FileField(blank=True, null=True, upload_to=fac.models.factura_xml_path),
        ),
    ]
    