"""
Django settings for admin project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# ALLOWED_HOSTS = [config('ALLOWED_HOSTS')]
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='').split(',')

# Application definition

INSTALLED_APPS = [
    'core',
    'inv',
    'cxc',
    'fac',
    'timbres',
    'widget_tweaks',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.TenantMiddleware',
]

ROOT_URLCONF = 'admin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.empresa_context',   
                'core.context_processors.site_messages',             
            ],
        },
    },
]

WSGI_APPLICATION = 'admin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config('DATABASE_NAME'),
        "USER": config('DATABASE_USER'),
        "PASSWORD": config('DATABASE_PASSWORD'),
        "HOST": config('DATABASE_HOST'),
        "PORT": config('DATABASE_PORT'),
    }
}


DATABASE_ROUTERS = ['core.db_router.TenantDatabaseRouter']

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es'

USE_TZ = True
TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/



STATICFILES_DIRS = [BASE_DIR / 'static'] 
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"  # destino de collectstatic
#STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Para collectstatic en producción

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



from django.urls import reverse_lazy

PASSWORD_RESET_TIMEOUT = 60 * 60  # 1 hora
LOGIN_URL = reverse_lazy('core:login')
LOGOUT_REDIRECT_URL = reverse_lazy('core:login')
LOGIN_REDIRECT_URL = reverse_lazy('core:inicio')

EMAIL_BACKEND = config('EMAIL_BACKEND')

AWS_SES_REGION_NAME=config('AWS_SES_REGION_NAME')
AWS_SES_REGION_ENDPOINT=config('AWS_SES_REGION_ENDPOINT')
AWS_ACCESS_KEY_ID=config('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY=config('AWS_SECRET_ACCESS_KEY')

#EMAIL_HOST = config('EMAIL_HOST')
#EMAIL_PORT = config('EMAIL_PORT')
#EMAIL_USE_TLS = config('EMAIL_USE_TLS') 
#EMAIL_HOST_USER = config('EMAIL_HOST_USER')
#EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")
DEFAULT_FROM_NAME = config("DEFAULT_FROM_NAME")
SERVER_EMAIL = config('SERVER_EMAIL')
REPLY_TO_EMAIL = config("REPLY_TO_EMAIL")
MAIL_TIMEOUT = config("EMAIL_TIMEOUT", cast=int, default=15)


SES_SANDBOX = config("SES_SANDBOX")
SES_PROD = config("SES_PROD", cast=bool, default=False)
SES_SANDBOX_WHITELIST = set([e.strip().lower() for e in config("SES_SANDBOX_WHITELIST", default="").split(",") if e.strip()])

PAC_CLIENT_ID = config('PAC_CLIENT_ID')
PAC_API_TOKEN = config('PAC_API_TOKEN')
PAC_URL = config('PAC_URL')

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# Seguridad para sesiones en desarrollo
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE')
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True
SESSION_SAVE_EVERY_REQUEST = False
SESSION_COOKIE_AGE = 7200  # Definir el tiempo que la sesión se mantiene activa. - 2 horas
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE')
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', cast=Csv())



# HSTS (HTTP Strict Transport Security)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS')
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Evita que el sitio se muestre en <iframe> (protección clickjacking)
X_FRAME_OPTIONS = 'DENY'

# Activa el header que impide que los navegadores infieran tipos MIME
SECURE_CONTENT_TYPE_NOSNIFF = True

# Previene que el navegador cargue scripts inseguros
SECURE_BROWSER_XSS_FILTER = True
SECURE_PROXY_SSL_HEADER = tuple(config(
    "SECURE_PROXY_SSL_HEADER",
    cast=Csv()
))
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT')

CELULAR = config('CEL_WA')

