# Generated by Django 4.2 on 2025-08-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoTimbresGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=7)),
                ('codigo_empresa', models.CharField(max_length=7)),
                ('usuario', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=1)),
                ('fecha', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='TimbresCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empresa', models.CharField(max_length=7)),
                ('total_asignados', models.BigIntegerField(default=0)),
                ('utilizados', models.BigIntegerField(default=0)),
                ('fecha_asignacion', models.DateField()),
            ],
        ),
    ]
    